name: .test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  zizmor:
    uses: ./.github/workflows/zizmor.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      zizmor_version: 1.5.2
