name: octoguard

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  zizmor:
    uses: ./.github/workflows/zizmor.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      zizmor_version: 1.5.2
